version: '3.8'

services:
  driver-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    runtime: nvidia  # Use NVIDIA runtime
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # For potential GUI testing
      - /usr/lib/wsl:/usr/lib/wsl  # For WSL compatibility if needed
    environment:
      - DISPLAY=${DISPLAY}  # For potential GUI testing
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    privileged: true  # Required for simulating hardware access
    cap_add:
      - SYS_ADMIN  # Required for system administration tasks
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["bash", "-c", "/app/test_driver.sh && /app/test_ollama.sh"]
